Repository TravelPouch/travelpouch, pull requests merged in 2024-10, with the labels that each got.

#1 docs: add figma link in the README.md
  README.md
Labels: documentation

#6 fix: close issue by updating package name to com.github.se.travelpouch
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/ExampleInstrumentedTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/screen/MainScreen.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/SecondActivity.kt
  app/src/main/java/com/github/se/travelpouch/SimpleData.kt
  app/src/main/java/com/github/se/travelpouch/resources/C.kt
  app/src/main/java/com/github/se/travelpouch/ui/theme/Color.kt
  app/src/main/java/com/github/se/travelpouch/ui/theme/Theme.kt
  app/src/main/java/com/github/se/travelpouch/ui/theme/Type.kt
  app/src/test/java/com/github/se/travelpouch/ExampleRobolectricTest.kt
  app/src/test/java/com/github/se/travelpouch/ExampleUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/PointTest.kt
  app/src/test/java/com/github/se/travelpouch/screen/SecondScreen.kt
  settings.gradle.kts
Labels: enhancement

#16 feat: add TravelContainer class, Firebase dependency and unit tests
  app/build.gradle.kts
  app/src/main/java/com/github/se/travelpouch/model/TravelContainer.kt
  app/src/test/java/com/github/se/travelpouch/TravelContainerUnitTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#25 chore: remove example files to improve coverage accuracy
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/travelpouch/SecondActivity.kt
  app/src/main/java/com/github/se/travelpouch/SimpleData.kt
  app/src/test/java/com/github/se/travelpouch/ExampleRobolectricTest.kt
  app/src/test/java/com/github/se/travelpouch/ExampleUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/PointTest.kt
  app/src/test/java/com/github/se/travelpouch/screen/SecondScreen.kt
Labels: enhancement

#28 fix(travelcontainer): Change behaviour of isValidUid
  app/src/main/java/com/github/se/travelpouch/model/TravelContainer.kt
  app/src/test/java/com/github/se/travelpouch/TravelContainerUnitTest.kt
Labels: bug

#29 feat: Implement ListTravelViewModel with CRUD operations and unit tests
  app/src/main/java/com/github/se/travelpouch/model/ListTravelViewModel.kt
  app/src/test/java/com/github/se/travelpouch/model/ListTravelViewModelUnitTest.kt
Labels: enhancement

#39 fix(travel-repository): add toMap method and correct time fields
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/MainActivityTest.kt
  app/src/main/java/com/github/se/travelpouch/model/TravelRepositoryFirestore.kt
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/github/se/travelpouch/model/TravelRepositoryFirestoreUnitTest.kt
Labels: bug

#48 Add Location Search and Dropdown in AddTravelScreen
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/ui/overview/AddTravelScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/model/location/LocationRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/location/LocationViewModel.kt
  app/src/main/java/com/github/se/travelpouch/model/location/NominatimLocationRepository.kt
  app/src/main/java/com/github/se/travelpouch/ui/overview/AddTravelScreen.kt
  app/src/test/java/com/github/se/travelpouch/model/location/LocationViewModelTest.kt
  app/src/test/java/com/github/se/travelpouch/model/location/NominatimLocationRepositoryTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#34 Add Sign-In Screen and Firebase Authentication
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/ui/authentication/GoogleSignInButtonTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/authentication/RememberFirebaseAuthLauncherUITest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/authentication/SignInViewTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/GoogleSignInButton.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/RememberFirebaseAuthLauncher.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt
  app/src/main/res/drawable/google_logo.png
  app/src/main/res/drawable/travelpouch_logo.png
  app/src/main/res/values/strings.xml
  app/src/test/java/com/github/se/travelpouch/model/ListTravelViewModelUnitTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#57 Gradle config to check ktfmt before each commit on Android Studio
  app/build.gradle.kts
Labels: enhancement

#94 Ci: Release build for CI
  .github/workflows/apk.yml
  app/build.gradle.kts
  app/proguard-rules.pro
Labels: bug

#105 Latest activities reminder banner #80
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/TravelActivityScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/NextActivitiesBanner.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
Labels: enhancement

#99 Add a Participant and copy email to clipboard buttons
  app/src/androidTest/java/com/github/se/travelpouch/ui/travel/EditTravelScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/model/ListTravelViewModel.kt
  app/src/main/java/com/github/se/travelpouch/model/TravelRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/TravelRepositoryFirestore.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantRow.kt
Labels: enhancement

#104 Feature/map activity display
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/map/CameraUpdater.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt
Labels: enhancement

#97 Feature/suggestion messages notification
  app/build.gradle.kts
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationContainer.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationContent.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationViewModel.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationContainerInvalidDataUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationContainerValidDataUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationContentUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationSimulationBetweenTwoUsers.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationViewModelUnitTest.kt
  gradle/libs.versions.toml
Labels: enhancement
