Repository TravelPouch/travelpouch, pull requests merged in 2024-11, with the labels that each got.

#110 Feature/map activity logic path
  app/src/main/java/com/github/se/travelpouch/model/activity/ActivityViewModel.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/ActivityModelViewUnitTest.kt
Labels: enhancement

#135 Feature/path activities data repository
  app/src/main/java/com/github/se/travelpouch/helper/NetworkManager.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsRepositoryInterface.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsResponse.kt
  app/src/main/java/com/github/se/travelpouch/model/location/NominatimLocationRepository.kt
  app/src/test/java/com/github/se/travelpouch/helper/NetworkManagerTest.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsRepositoryTest.kt
  app/src/test/java/com/github/se/travelpouch/model/location/NominatimLocationRepositoryUnitTest.kt
Labels: enhancement

#148 refactor: delete notification simulation test
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationSimulationBetweenTwoUsers.kt
Labels: bug

#131 feature: add app logo and name to the application
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher_travelpouch-playstore.png
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_travelpouch.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_travelpouch_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_travelpouch.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_travelpouch_foreground.webp
  app/src/main/res/mipmap-hdpi/ic_launcher_travelpouch_round.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_travelpouch.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_travelpouch_foreground.webp
  app/src/main/res/mipmap-mdpi/ic_launcher_travelpouch_round.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_travelpouch.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_travelpouch_foreground.webp
  app/src/main/res/mipmap-xhdpi/ic_launcher_travelpouch_round.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_travelpouch.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_travelpouch_foreground.webp
  app/src/main/res/mipmap-xxhdpi/ic_launcher_travelpouch_round.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_travelpouch.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_travelpouch_foreground.webp
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_travelpouch_round.webp
  app/src/main/res/values/ic_launcher_travelpouch_background.xml
Labels: enhancement

#144 fix: fix the timePickerDialog
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/AddActivityScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
Labels: bug

#138 feat: add ViewModel for handling Google Maps directions
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModel.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModelTest.kt
Labels: enhancement

#149 feat: UI display images in an activity
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/TravelActivityScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
Labels: enhancement

#165 fix: update the name app to TravelPouch
  app/src/main/AndroidManifest.xml
Labels: bug

#163 Feature/date picker
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/AddActivityScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/EditActivityScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/AddTravelScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/travel/EditTravelScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/AddTravel.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
  app/src/main/java/com/github/se/travelpouch/utils/DateTimeUtils.kt
  app/src/test/java/com/github/se/travelpouch/helper/DateTimeUtilsTest.kt
Labels: enhancement

#172 Fix/map display travel list
  app/src/main/java/com/github/se/travelpouch/ui/home/Map.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
Labels: bug

#167 test: E2E
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/HiltTestRunner.kt
  app/src/androidTest/java/com/github/se/travelpouch/di/TestModule.kt
  app/src/androidTest/java/com/github/se/travelpouch/endtoend/EndToEndTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/authentication/SignInViewTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/authentication/TestSignInEmailPasswordUI.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/TravelPouchApp.kt
  app/src/main/java/com/github/se/travelpouch/di/AppModules.kt
  app/src/main/java/com/github/se/travelpouch/di/Database.kt
  app/src/main/java/com/github/se/travelpouch/model/authentication/AuthenticationService.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/profile/ProfileModelView.kt
  app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepositoryMock.kt
  app/src/main/java/com/github/se/travelpouch/model/travels/ListTravelViewModel.kt
  app/src/main/java/com/github/se/travelpouch/model/travels/TravelRepositoryMock.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignInWithPassword.kt
  app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentList.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/AddTravel.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt
  app/src/test/java/com/github/se/travelpouch/model/authentication/TestSignInWithEmailAndPassword.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/profile/ProfileRepositoryMockTest.kt
  app/src/test/java/com/github/se/travelpouch/model/travel/TravelRepositoryMockTest.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: test

#176 Fix: text fields are not visible on edit and participant list
  app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantRow.kt
Labels: bug

#174 feat: ask the permission to access folder only once per session
  app/src/androidTest/java/com/github/se/travelpouch/ui/documents/StoreDocumentButtonTest.kt
  app/src/main/java/com/github/se/travelpouch/model/documents/DocumentViewModel.kt
  app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentPreview.kt
  app/src/main/java/com/github/se/travelpouch/ui/documents/StoreDocumentButton.kt
  app/src/test/java/com/github/se/travelpouch/model/documents/DocumentViewModelTest.kt
Labels: enhancement

#201 UI theme and coherency
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/Calendar.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/NextActivitiesBanner.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentPreview.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/AddTravel.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/profile/ModifyingProfileScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/profile/ProfileScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/theme/Theme.kt
  app/src/main/java/com/github/se/travelpouch/ui/theme/Type.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantListScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantRow.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/TruncatedText.kt
Labels: enhancement

#145 Feature/notification UI with refactor
  app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationItemTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/travel/EditTravelScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/travel/ParticipantListScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryFirestore.kt
  app/src/main/java/com/github/se/travelpouch/model/notifications/NotificationViewModel.kt
  app/src/main/java/com/github/se/travelpouch/model/profile/ProfileModelView.kt
  app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepositoryFirebase.kt
  app/src/main/java/com/github/se/travelpouch/model/profile/ProfileRepositoryMock.kt
  app/src/main/java/com/github/se/travelpouch/model/travels/ListTravelViewModel.kt
  app/src/main/java/com/github/se/travelpouch/model/travels/TravelRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/travels/TravelRepositoryFirestore.kt
  app/src/main/java/com/github/se/travelpouch/model/travels/TravelRepositoryMock.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationItem.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationsScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantListScreen.kt
  app/src/main/res/drawable/ic_message.xml
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationContainerValidDataUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryFirestoreUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationRepositoryUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/notifications/NotificationViewModelUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/profile/ProfileRepositoryTest.kt
  app/src/test/java/com/github/se/travelpouch/model/travel/ListTravelViewModelUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/travel/TravelRepositoryFirestoreUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/ui/notification/NotificationScreenUnitTest.kt
  gradle/wrapper/gradle-wrapper.properties
Labels: enhancement

#199 Feature/activities path waypoint
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsRepositoryInterface.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsResponse.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModel.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsRepositoryTest.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModelTest.kt
Labels: enhancement

#197 Feature: Sign-in persistence
  app/src/androidTest/java/com/github/se/travelpouch/ui/authentication/SignInViewTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
Labels: enhancement

#212 Feature/implementation swipe
  app/src/androidTest/java/com/github/se/travelpouch/endtoend/EndToEndTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/CalendarScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/TravelListScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/navigation/PagerSwipeTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/Calendar.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/SwipePager.kt
  app/src/main/java/com/github/se/travelpouch/ui/profile/ProfileScreen.kt
Labels: enhancement

#213 Feature/path-activities
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsRepositoryInterface.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModel.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreen.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsRepositoryTest.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModelTest.kt
Labels: enhancement

#221 UI: Fix notification screen light/dark theme handling and UI coherency
  app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationItem.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationsScreen.kt
Labels: bug

#219 UI: Stow away map and clickable map waypoint
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/TravelListScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/Map.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
Labels: enhancement

#222 Feature : floating navigation drawer home button
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/TravelListScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/navigation/PagerSwipeTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/NavigationActions.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/SwipePager.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationItem.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationsScreen.kt
  app/src/main/java/com/github/se/travelpouch/ui/profile/ProfileScreen.kt
Labels: enhancement
