Repository TravelPouch/travelpouch, pull requests merged in 2024-12, with the labels that each got.

#234 Feature/path activities gps
  app/build.gradle.kts
  app/src/androidTest/java/com/github/se/travelpouch/permissions/LocationPermissionComposableTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModel.kt
  app/src/main/java/com/github/se/travelpouch/model/gps/GPSRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/gps/GPSViewModel.kt
  app/src/main/java/com/github/se/travelpouch/permissions/LocationPermissionComposable.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreen.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModelTest.kt
  app/src/test/java/com/github/se/travelpouch/model/gps/GPSViewModelTest.kt
  gradle/libs.versions.toml
Labels: enhancement

#235 feat(logout): Add logout entry and logout logic
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/TravelListScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/theme/Color.kt
Labels: enhancement

#248 feat: add BottomSheet to display informations
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModel.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreen.kt
Labels: enhancement

#251 E2E test for activity
  .github/workflows/ci.yml
  app/src/androidTest/java/com/github/se/travelpouch/e2e/ActivityCreationAndEdit.kt
  app/src/androidTest/java/com/github/se/travelpouch/e2e/DocumentUpload.kt
  app/src/androidTest/java/com/github/se/travelpouch/e2e/TravelCreation.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/EditActivityScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/TravelActivityScreen.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/travel/ParticipantListScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/fields/DateTimeInputField.kt
  app/src/main/java/com/github/se/travelpouch/ui/fields/LocationQueryField.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/EditTravelSettings.kt
  app/src/main/java/com/github/se/travelpouch/ui/travel/ParticipantListScreen.kt
Labels: test

#263 feat: add travel mode in ActivitiesMapScreen
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModel.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreen.kt
Labels: enhancement

#261 test: Adding an e2e tests that adds a participant through notifications
  app/src/androidTest/java/com/github/se/travelpouch/e2e/ProfileNotificationTest.kt
Labels: test

#265 UI and UX improvements
  app/src/androidTest/java/com/github/se/travelpouch/ui/notification/NotificationItemTest.kt
  app/src/main/java/com/github/se/travelpouch/ui/authentication/SignIn.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/CalendarViewComposable.kt
  app/src/main/java/com/github/se/travelpouch/ui/home/TravelList.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationItem.kt
  app/src/main/java/com/github/se/travelpouch/ui/notifications/NotificationsScreen.kt
Labels: bug

#267 feat: Implementing the linking between documents and activities
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/AddActivityScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/EditActivityScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/TravelActivityScreen.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/dashboard/map/ActivitiesMapScreenTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/documents/DocumentPreviewTest.kt
  app/src/androidTest/java/com/github/se/travelpouch/ui/home/CalendarScreenTest.kt
  app/src/main/java/com/github/se/travelpouch/MainActivity.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/Activity.kt
  app/src/main/java/com/github/se/travelpouch/model/activity/ActivityRepositoryFirebase.kt
  app/src/main/java/com/github/se/travelpouch/model/documents/DocumentRepository.kt
  app/src/main/java/com/github/se/travelpouch/model/documents/DocumentViewModel.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/AddActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/EditActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/dashboard/TravelActivity.kt
  app/src/main/java/com/github/se/travelpouch/ui/documents/DocumentPreview.kt
  app/src/main/java/com/github/se/travelpouch/ui/navigation/SwipePager.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/ActivityModelViewUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/ActivityRepositoryUnitTest.kt
  app/src/test/java/com/github/se/travelpouch/model/activity/map/DirectionsViewModelTest.kt
  app/src/test/java/com/github/se/travelpouch/model/documents/DocumentRepositoryTest.kt
  app/src/test/java/com/github/se/travelpouch/model/documents/DocumentViewModelTest.kt
Labels: enhancement
